import { Button, ButtonType } from './types';

export const schema: Button[] = [
  { type: ButtonType.CLEAR },
  { type: ButtonType.OPERATOR, priority: 3, value: '^', inputValue: '^', eval: (num1, num2): number => Math.pow(num1, num2) },
  { type: ButtonType.OPERATOR, priority: 2, value: '%', inputValue: '%', eval: (num1, num2): number => num1 % num2 },
  { type: ButtonType.CLEAR_ONE },
  { type: ButtonType.OPERATOR, priority: 2, value: '/', inputValue: '/', eval: (num1, num2): number => num1 / num2 },
  { type: ButtonType.OPERATOR, priority: 3, value: '√', inputValue: '2√', eval: (num1, num2): number => Math.pow(num2, 1 / num1) },
  { type: ButtonType.CHAR, value: '(' },
  { type: ButtonType.CHAR, value: ')' },
  { type: ButtonType.CHAR, value: '7' },
  { type: ButtonType.CHAR, value: '8' },
  { type: ButtonType.CHAR, value: '9' },
  { type: ButtonType.OPERATOR, priority: 2, value: '*', inputValue: '*', eval: (num1, num2): number => num1 * num2 },
  { type: ButtonType.CHAR, value: '4' },
  { type: ButtonType.CHAR, value: '5' },
  { type: ButtonType.CHAR, value: '6' },
  {
    type: ButtonType.OPERATOR,
    priority: 1,
    value: '-',
    inputValue: '-',
    eval: (num1, num2): number => num1 - num2,
  },
  { type: ButtonType.CHAR, value: '1' },
  { type: ButtonType.CHAR, value: '2' },
  { type: ButtonType.CHAR, value: '3' },
  { type: ButtonType.OPERATOR, priority: 1, value: '+', inputValue: '+', eval: (num1, num2): number => num1 + num2 },
  { type: ButtonType.CHAR, value: '00' },
  { type: ButtonType.CHAR, value: '0' },
  { type: ButtonType.CHAR, value: '.' },
  { type: ButtonType.EQUAL },
];
